modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]]
modId="playerreset"
version="${file.jarVersion}"
displayName="Vault Hunters Player Reset"
logoFile="logo.png"
authors="Gargoyle3333"

description='''
This mod adds extra commands to reset a player's vault data.

The all command will completely reset a player. Alternatively, each step the all command performs is available on its
own, so a player's workbench modifiers can be reset. Check the README for the full list of commands.
'''

[[dependencies.playerreset]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.playerreset]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"

[[dependencies.playerreset]]
modId="the_vault"
mandatory=true
versionRange="[1.18.2-3.11.0.2514,)"
ordering="AFTER"
side="SERVER"
